### ISSUE TITLE
Testing and building fails

### ISSUE THREAD

**Issue by mwaa** [maidsafe/safe_dns#40]
cargo test --features "use-mock-routing" fails with cannot build safe_dns. My environment is windows 10 not sure if its something missing. Error might reflect a change in safe_nfs which has not been implemented in dns.

![error_dns](https://cloud.githubusercontent.com/assets/5112468/9832387/22eb5430-5982-11e5-86f1-3e22450997d9.jpg)

**Comment by ustulation** [comment]
MAID-1318 was designed for this .. That's merged .. should be fine now.

https://github.com/maidsafe/safe_dns/pull/42
