### ISSUE TITLE
Typo on "get_housing_sturctured_data_and_dns_record" function

### ISSUE THREAD

**Issue by loureirorg** [maidsafe/safe_dns#62]
there's a typo on the `get_housing_sturctured_data_and_dns_record` function (notice the "_sturctured_" word).

https://github.com/maidsafe/safe_dns/blob/master/src/dns_operations/mod.rs#L233

**Comment by ustulation** [comment]
Ah not the function name!! what a gaffe 😞  .. Thanks for pointing out. The saving grace is that it's not a public function so confined to this file hopefully. Will get it done.
